lab1 : lab1.c lab1_1 lab1_2 lab1_3
		cc -o lab1 lab1.c

lab1_1 : lab1_1.cpp
		g++ -std=c++11 -o lab1_1 lab1_1.cpp

lab1_2 : lab1_2.cpp
		g++ -std=c++11 -o lab1_2 lab1_2.cpp

lab1_3 : lab1_3.cpp
		g++ -std=c++11 -o lab1_3 lab1_3.cpp

clean :
		rm  lab1 lab1_1 lab1_2 lab1_3